# [nfs]
# 172.31.46.243 ansible_ssh_user='ec2-user'

[webservers]
172.31.33.161 ansible_ssh_user='ec2-user'
172.31.42.164 ansible_ssh_user='ec2-user'

# [db]
# 172.31.34.52 ansible_ssh_user='ubuntu' 

# [lb]
# 172.31.37.55 ansible_ssh_user='ubuntu'